import { StyleSheet } from 'react-native';

export const createStyles = (colors: any) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: colors.background,
    },
    messagesContainer: {
      flex: 1,
    },
    emptyState: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      paddingVertical: 60,
    },
    emptyStateIcon: {
      fontSize: 64,
      marginBottom: 16,
    },
    emptyStateText: {
      fontSize: 18,
      fontWeight: '600',
      color: colors.text || '#2C2C2C',
      marginBottom: 8,
    },
    emptyStateSubtext: {
      fontSize: 14,
      color: colors.textSecondary || '#666',
      textAlign: 'center',
      paddingHorizontal: 40,
    },
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      padding: 16,
      backgroundColor: colors.primary,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 3,
    },
    backButton: {
      padding: 8,
      width: 40,
      height: 40,
      borderRadius: 20,
      backgroundColor: 'rgba(255,255,255,0.2)',
      alignItems: 'center',
      justifyContent: 'center',
    },
    backText: {
      color: 'white',
      fontSize: 24,
      fontWeight: 'bold',
    },
    headerTitle: {
      flex: 1,
      textAlign: 'center',
      color: 'white',
      fontSize: 18,
      fontWeight: 'bold',
    },
    message: {
      marginBottom: 16,
      padding: 16,
      borderRadius: 16,
      maxWidth: '85%',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 2,
    },
    userMessage: {
      alignSelf: 'flex-end',
      backgroundColor: colors.primary,
      borderBottomRightRadius: 4,
    },
    aiMessage: {
      alignSelf: 'flex-start',
      backgroundColor: colors.surface || '#f5f5f5',
      borderBottomLeftRadius: 4,
      borderLeftWidth: 3,
      borderLeftColor: '#6B4423',
    },
    messageText: {
      fontSize: 15,
      lineHeight: 22,
    },
    userText: {
      color: 'white',
    },
    aiText: {
      color: colors.text || '#2C2C2C',
    },
    inputRow: {
      flexDirection: 'row',
      padding: 16,
      borderTopWidth: 1,
      borderColor: colors.border || '#E0E0E0',
      backgroundColor: colors.background,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: -2 },
      shadowOpacity: 0.05,
      shadowRadius: 4,
      elevation: 4,
    },
    devicePickerContainer: {
      backgroundColor: colors.surface || '#f5f5f5',
      paddingHorizontal: 16,
      paddingVertical: 12,
      borderBottomWidth: 1,
      borderBottomColor: colors.border || '#E0E0E0',
      flexDirection: 'row',
      alignItems: 'center',
    },
    devicePickerLabel: {
      fontSize: 15,
      fontWeight: '600',
      color: colors.text || '#2C2C2C',
      marginRight: 8,
    },
    devicePicker: {
      flex: 1,
      height: 40,
    },
    input: {
      flex: 1,
      borderWidth: 1,
      borderColor: colors.border || '#E0E0E0',
      borderRadius: 24,
      paddingHorizontal: 16,
      paddingVertical: 12,
      backgroundColor: colors.surface || '#f5f5f5',
      fontSize: 15,
      color: colors.text || '#2C2C2C',
    },
    sendButton: {
      marginLeft: 12,
      backgroundColor: colors.primary,
      paddingHorizontal: 24,
      paddingVertical: 12,
      justifyContent: 'center',
      borderRadius: 24,
      shadowColor: colors.primary,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.3,
      shadowRadius: 4,
      elevation: 3,
    },
    sendText: {
      color: '#fff',
      fontWeight: 'bold',
    },
    offlineBadge: {
      marginTop: 6,
      alignSelf: 'flex-start',
      backgroundColor: '#f9d67a',
      borderRadius: 6,
      paddingHorizontal: 8,
      paddingVertical: 2,
    },
    offlineBadgeText: {
      fontSize: 12,
      color: '#4a3b0b',
      fontWeight: '600',
    },
  });
