import { StyleSheet } from 'react-native';

export const createStyles = (colors: any) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: colors.background,
    },
    messagesContainer: {
      flex: 1,
    },
    emptyState: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      paddingVertical: 60,
    },
    emptyStateIcon: {
      fontSize: 64,
      marginBottom: 16,
    },
    emptyStateText: {
      fontSize: 18,
      fontWeight: '600',
      color: colors.text || '#2C2C2C',
      marginBottom: 8,
    },
    emptyStateSubtext: {
      fontSize: 14,
      color: colors.textSecondary || '#666',
      textAlign: 'center',
      paddingHorizontal: 40,
    },
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      padding: 16,
      backgroundColor: colors.primary,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 3,
    },
    backButton: {
      padding: 8,
      width: 40,
      height: 40,
      borderRadius: 20,
      backgroundColor: 'rgba(255,255,255,0.2)',
      alignItems: 'center',
      justifyContent: 'center',
    },
    backText: {
      color: 'white',
      fontSize: 24,
      fontWeight: 'bold',
    },
    headerTitle: {
      flex: 1,
      textAlign: 'center',
      color: 'white',
      fontSize: 18,
      fontWeight: 'bold',
    },
    message: {
      marginBottom: 16,
      padding: 16,
      borderRadius: 16,
      maxWidth: '85%',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 2,
    },
    userMessage: {
      alignSelf: 'flex-end',
      backgroundColor: colors.primary,
      borderBottomRightRadius: 4,
    },
    aiMessage: {
      alignSelf: 'flex-start',
      backgroundColor: colors.surface || '#f5f5f5',
      borderBottomLeftRadius: 4,
      borderLeftWidth: 3,
      borderLeftColor: '#6B4423',
    },
    messageText: {
      fontSize: 15,
      lineHeight: 22,
    },
    userText: {
      color: 'white',
    },
    aiText: {
      color: colors.text || '#2C2C2C',
    },
    inputRow: {
      flexDirection: 'row',
      padding: 16,
      borderTopWidth: 1,
      borderColor: colors.border || '#E0E0E0',
      backgroundColor: colors.background,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: -2 },
      shadowOpacity: 0.05,
      shadowRadius: 4,
      elevation: 4,
    },
    devicePickerContainer: {
      backgroundColor: colors.surface || '#f5f5f5',
      paddingHorizontal: 16,
      paddingVertical: 12,
      borderBottomWidth: 1,
      borderBottomColor: colors.border || '#E0E0E0',
      flexDirection: 'row',
      alignItems: 'center',
    },
    devicePickerLabel: {
      fontSize: 15,
      fontWeight: '600',
      color: colors.text || '#2C2C2C',
      marginRight: 8,
    },
    devicePicker: {
      flex: 1,
      height: 40,
    },
    input: {
      flex: 1,
      borderWidth: 1,
      borderColor: colors.border || '#E0E0E0',
      borderRadius: 24,
      paddingHorizontal: 16,
      paddingVertical: 12,
      backgroundColor: colors.surface || '#f5f5f5',
      fontSize: 15,
      color: colors.text || '#2C2C2C',
    },
    sendButton: {
      marginLeft: 12,
      backgroundColor: colors.primary,
      paddingHorizontal: 24,
      paddingVertical: 12,
      justifyContent: 'center',
      borderRadius: 24,
      shadowColor: colors.primary,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.3,
      shadowRadius: 4,
      elevation: 3,
    },
    sendText: {
      color: '#fff',
      fontWeight: 'bold',
    },
    offlineBadge: {
      marginTop: 6,
      alignSelf: 'flex-start',
      backgroundColor: '#f9d67a',
      borderRadius: 6,
      paddingHorizontal: 8,
      paddingVertical: 2,
    },
    offlineBadgeText: {
      fontSize: 12,
      color: '#4a3b0b',
      fontWeight: '600',
    },
    // Recipe card styles
    recipeContainer: {
      marginBottom: 16,
      width: '100%',
    },
    recipeCard: {
      borderRadius: 24,
      padding: 20,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.12,
      shadowRadius: 8,
      elevation: 4,
      borderWidth: 1,
      borderColor: '#FFE4D1',
    },
    recipeHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 20,
      paddingBottom: 16,
      borderBottomWidth: 2,
      borderBottomColor: '#FFD4B3',
    },
    recipeHeaderIcon: {
      fontSize: 32,
      marginRight: 12,
    },
    recipeHeaderText: {
      fontSize: 22,
      fontWeight: '700',
      color: '#6B4423',
    },
    recipeSection: {
      marginBottom: 20,
    },
    introSection: {
      marginBottom: 16,
      padding: 16,
      backgroundColor: '#FFF5ED',
      borderRadius: 16,
      borderLeftWidth: 4,
      borderLeftColor: '#D4A574',
    },
    introText: {
      fontSize: 16,
      lineHeight: 24,
      color: '#5A3825',
      marginBottom: 8,
    },
    sectionHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 12,
    },
    sectionIcon: {
      fontSize: 24,
      marginRight: 10,
    },
    sectionTitle: {
      fontSize: 18,
      fontWeight: '700',
      color: '#6B4423',
    },
    ingredientsGrid: {
      gap: 10,
    },
    ingredientChip: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: '#FFFFFF',
      paddingVertical: 12,
      paddingHorizontal: 16,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: '#FFD4B3',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.08,
      shadowRadius: 4,
      elevation: 2,
    },
    ingredientBullet: {
      fontSize: 18,
      color: '#D4A574',
      marginRight: 12,
      fontWeight: '700',
    },
    ingredientText: {
      fontSize: 15,
      color: '#5A3825',
      flex: 1,
      lineHeight: 22,
    },
    stepsContainer: {
      gap: 12,
    },
    stepCard: {
      flexDirection: 'row',
      backgroundColor: '#FFFFFF',
      padding: 16,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: '#FFD4B3',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.08,
      shadowRadius: 4,
      elevation: 2,
    },
    stepNumber: {
      width: 36,
      height: 36,
      borderRadius: 18,
      backgroundColor: '#6B4423',
      alignItems: 'center',
      justifyContent: 'center',
      marginRight: 12,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.15,
      shadowRadius: 3,
      elevation: 2,
    },
    stepNumberText: {
      fontSize: 16,
      fontWeight: '700',
      color: '#FFFFFF',
    },
    stepText: {
      flex: 1,
      fontSize: 15,
      lineHeight: 22,
      color: '#5A3825',
    },
    tipsContainer: {
      backgroundColor: '#FFF8E7',
      borderRadius: 16,
      padding: 16,
      borderWidth: 1,
      borderColor: '#FFE4B3',
    },
    tipItem: {
      marginBottom: 12,
      paddingLeft: 8,
    },
    tipText: {
      fontSize: 14,
      lineHeight: 20,
      color: '#5A3825',
      fontStyle: 'italic',
    },
  });
