import { PredictionContext, PredictionResult } from 'types/Personalization.ts';

/**
 * Contract describing telemetry hooks invoked during recommendation generation and cache usage.
 */
export interface RecommendationTelemetry {
  /**
   * Records that a new recommendation payload was generated by the engine.
   *
   * @param {string} userId - Identifier of the user for whom the recommendation was produced.
   * @param {PredictionContext} context - Context used in generating the recommendation.
   * @param {PredictionResult} prediction - Primary prediction result that was generated.
   */
  recordGenerated: (userId: string, context: PredictionContext, prediction: PredictionResult) => void;
  /**
   * Records that a cached recommendation was returned for the given context.
   *
   * @param {string} userId - Identifier of the user receiving the cached recommendation.
   * @param {PredictionContext} context - Context matched against the cache entry.
   */
  recordCacheHit: (userId: string, context: PredictionContext) => void;
  /**
   * Records that travel mode impacted recommendation logic for observability purposes.
   */
  recordTravelMode: () => void;
}

/**
 * Default in-memory telemetry implementation allowing listeners to subscribe to recommendation events.
 */
export class DefaultRecommendationTelemetry implements RecommendationTelemetry {
  private readonly listeners: Array<(event: RecommendationTelemetryEvent) => void> = [];

  /**
   * Registers a listener to receive telemetry events.
   *
   * @param {(event: RecommendationTelemetryEvent) => void} listener - Callback invoked with each emitted telemetry event.
   * @returns {void}
   */
  public addListener(listener: (event: RecommendationTelemetryEvent) => void): void {
    this.listeners.push(listener);
  }

  /**
   * Emits a telemetry event indicating that a new recommendation was generated.
   *
   * @param {string} userId - User identifier for whom recommendations were produced.
   * @param {PredictionContext} context - Context payload used to produce the recommendation.
   * @param {PredictionResult} prediction - Generated prediction detail.
   * @returns {void}
   */
  public recordGenerated(userId: string, context: PredictionContext, prediction: PredictionResult): void {
    this.emit({ type: 'generated', userId, context, prediction });
  }

  /**
   * Emits a telemetry event indicating that a cached recommendation was served.
   *
   * @param {string} userId - User identifier requesting recommendations.
   * @param {PredictionContext} context - Context data matching the cached entry.
   * @returns {void}
   */
  public recordCacheHit(userId: string, context: PredictionContext): void {
    this.emit({ type: 'cache-hit', userId, context });
  }

  /**
   * Emits a telemetry event indicating travel mode was detected during recommendation processing.
   *
   * @returns {void}
   */
  public recordTravelMode(): void {
    this.emit({ type: 'travel-mode' });
  }

  /**
   * Notifies all registered listeners with the provided telemetry event payload.
   *
   * @param {RecommendationTelemetryEvent} event - Telemetry event to propagate to listeners.
   * @returns {void}
   */
  private emit(event: RecommendationTelemetryEvent): void {
    this.listeners.forEach((listener) => listener(event));
  }
}

export type RecommendationTelemetryEvent =
  | { type: 'generated'; userId: string; context: PredictionContext; prediction: PredictionResult }
  | { type: 'cache-hit'; userId: string; context: PredictionContext }
  | { type: 'travel-mode' };
