// ProfessionalOCRScanner.styles.ts - BrewMate Material-inspired design
import { StyleSheet, Platform } from 'react-native';

const palette = {
  primary: '#6B4423',
  primaryDark: '#4A2F18',
  accent: '#FF8C42',
  accentDark: '#D06020',
  cream: '#F5E6D3',
  background: '#FAF8F5',
  surface: '#FFFFFF',
  surfaceElevated: '#FFF9F5',
  textPrimary: '#2C1810',
  textSecondary: '#5D4E37',
  textTertiary: '#8B7355',
  success: '#7FB069',
  warning: '#FFA000',
  danger: '#E84855',
  border: '#E8DED4',
  borderLight: '#F0E6DC',
  shadow: 'rgba(107, 68, 35, 0.15)',
};

const baseShadow = {
  shadowColor: palette.shadow,
  shadowOffset: { width: 0, height: 12 },
  shadowOpacity: 0.12,
  shadowRadius: 24,
  elevation: 8,
};

export const scannerStyles = (_isDarkMode: boolean = false) => {
  return StyleSheet.create({
    screen: {
      flex: 1,
      backgroundColor: palette.background,
    },
    flex: {
      flex: 1,
    },
    backgroundGradient: {
      ...StyleSheet.absoluteFillObject,
    },
    scrollView: {
      flex: 1,
    },
    scrollContent: {
      flexGrow: 1,
      paddingBottom: 160,
    },
    contentWrapper: {
      flex: 1,
      paddingHorizontal: 0,
      paddingVertical: 0,
    },
    phoneContainer: {
      flex: 1,
      width: '100%',
      alignSelf: 'stretch',
      backgroundColor: palette.surface,
      borderRadius: 0,
      borderWidth: 0,
      overflow: 'hidden',
    },
    statusBar: {
      paddingHorizontal: 24,
      paddingTop: Platform.OS === 'ios' ? 20 : 16,
      paddingBottom: 8,
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      alignSelf: 'stretch',
    },
    statusTime: {
      fontSize: 14,
      fontWeight: '600',
      color: palette.textPrimary,
    },
    statusIcons: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
    },
    statusIcon: {
      fontSize: 14,
    },
    appHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: 20,
      paddingBottom: 16,
      borderBottomWidth: 1,
      borderBottomColor: palette.borderLight,
      backgroundColor: palette.surface,
    },
    backButton: {
      width: 40,
      height: 40,
      borderRadius: 12,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: 'rgba(255,255,255,0.75)',
      borderWidth: 1,
      borderColor: 'rgba(139, 111, 71, 0.08)',
      opacity: 0,
      transform: [{ translateX: -16 }],
    },
    backButtonVisible: {
      opacity: 1,
      transform: [{ translateX: 0 }],
    },
    backButtonText: {
      fontSize: 18,
      color: palette.textPrimary,
    },
    headerContent: {
      flex: 1,
      marginLeft: 12,
    },
    headerRow: {
      flexDirection: 'row',
      alignItems: 'center',
    },
    coffeeIcon: {
      fontSize: 20,
      marginRight: 8,
    },
    headerTitle: {
      fontSize: 22,
      fontWeight: '700',
      color: palette.textPrimary,
      letterSpacing: -0.3,
    },
    headerSubtitle: {
      fontSize: 12,
      color: palette.textTertiary,
      marginTop: 4,
    },
    mainContent: {
      paddingHorizontal: 20,
      paddingVertical: 24,
      backgroundColor: palette.background,
    },
    welcomeCard: {
      borderRadius: 24,
      padding: 24,
      marginBottom: 24,
      overflow: 'hidden',
    },
    welcomeEmoji: {
      fontSize: 44,
      marginBottom: 12,
      color: '#FFFFFF',
    },
    welcomeText: {
      fontSize: 24,
      fontWeight: '700',
      color: '#FFFFFF',
      marginBottom: 8,
    },
    welcomeDesc: {
      fontSize: 14,
      color: 'rgba(255,255,255,0.9)',
      lineHeight: 20,
    },
    actionSection: {
      marginBottom: 24,
    },
    actionGrid: {
      flexDirection: 'row',
      gap: 12,
    },
    actionCard: {
      flex: 1,
      backgroundColor: palette.surface,
      borderRadius: 20,
      paddingVertical: 24,
      alignItems: 'center',
      borderWidth: 1,
      borderColor: palette.borderLight,
      ...baseShadow,
    },
    actionCardPrimary: {
      borderColor: 'transparent',
    },
    actionIconContainer: {
      width: 56,
      height: 56,
      borderRadius: 16,
      backgroundColor: palette.cream,
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: 12,
    },
    actionIconContainerPrimary: {
      borderRadius: 16,
    },
    actionIcon: {
      fontSize: 28,
    },
    actionLabel: {
      fontSize: 15,
      fontWeight: '700',
      color: palette.textPrimary,
      marginBottom: 4,
    },
    actionSublabel: {
      fontSize: 12,
      color: palette.textTertiary,
    },
    statsContainer: {
      flexDirection: 'row',
      justifyContent: 'space-around',
      alignItems: 'center',
      marginBottom: 24,
      paddingVertical: 20,
      borderRadius: 20,
      backgroundColor: 'rgba(255,255,255,0.75)',
      borderWidth: 1,
      borderColor: 'rgba(139, 111, 71, 0.08)',
      ...baseShadow,
    },
    statItem: {
      alignItems: 'center',
      flex: 1,
    },
    statNumber: {
      fontSize: 24,
      fontWeight: '800',
      color: palette.textPrimary,
    },
    statLabel: {
      fontSize: 11,
      color: palette.textTertiary,
      marginTop: 4,
      textTransform: 'uppercase',
      letterSpacing: 0.6,
    },
    statDivider: {
      width: 1,
      height: '80%',
      backgroundColor: palette.border,
      opacity: 0.6,
    },
    historySection: {
      marginBottom: 24,
    },
    historyHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginBottom: 12,
    },
    historyTitle: {
      fontSize: 18,
      fontWeight: '700',
      color: palette.textPrimary,
    },
    historySeeAll: {
      paddingHorizontal: 8,
      paddingVertical: 4,
      borderRadius: 12,
    },
    historySeeAllText: {
      fontSize: 13,
      color: palette.accent,
      fontWeight: '600',
    },
    historyGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      justifyContent: 'space-between',
      rowGap: 12,
    },
    historyCard: {
      width: '48%',
      backgroundColor: palette.surface,
      borderRadius: 16,
      padding: 16,
      borderWidth: 1,
      borderColor: palette.borderLight,
      overflow: 'hidden',
      ...baseShadow,
    },
    historyCardAccent: {
      position: 'absolute',
      top: 0,
      left: 0,
      width: 4,
      height: '100%',
      backgroundColor: palette.accent,
    },
    historyCardContent: {
      marginLeft: 8,
    },
    historyCardName: {
      fontSize: 14,
      fontWeight: '700',
      color: palette.textPrimary,
      marginBottom: 4,
    },
    historyCardDate: {
      fontSize: 11,
      color: palette.textTertiary,
      marginBottom: 6,
    },
    historyCardRating: {
      fontSize: 12,
      color: palette.warning,
    },
    emptyState: {
      alignItems: 'center',
      paddingVertical: 48,
      paddingHorizontal: 16,
    },
    emptyStateImage: {
      width: 100,
      height: 100,
      borderRadius: 50,
      backgroundColor: palette.cream,
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: 16,
      ...baseShadow,
    },
    emptyStateIcon: {
      fontSize: 42,
    },
    emptyStateTitle: {
      fontSize: 18,
      fontWeight: '700',
      color: palette.textPrimary,
      marginBottom: 8,
    },
    emptyStateDesc: {
      fontSize: 14,
      color: palette.textTertiary,
      textAlign: 'center',
      lineHeight: 20,
    },
    resultSection: {
      marginBottom: 20,
    },
    resultCard: {
      backgroundColor: palette.surface,
      borderRadius: 20,
      padding: 20,
      borderWidth: 1,
      borderColor: palette.borderLight,
      ...baseShadow,
    },
    resultHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 12,
    },
    resultTitle: {
      fontSize: 16,
      fontWeight: '700',
      color: palette.textPrimary,
    },
    matchBadge: {
      paddingHorizontal: 12,
      paddingVertical: 6,
      borderRadius: 12,
    },
    matchBadgeGood: {
      backgroundColor: palette.success,
    },
    matchBadgeFair: {
      backgroundColor: palette.warning,
    },
    matchText: {
      color: '#FFFFFF',
      fontSize: 12,
      fontWeight: '700',
    },
    resultTextInput: {
      minHeight: 120,
      borderRadius: 16,
      padding: 16,
      borderWidth: 1,
      borderColor: palette.borderLight,
      backgroundColor: palette.surfaceElevated,
      fontSize: 14,
      color: palette.textPrimary,
      lineHeight: 20,
    },
    recommendationCard: {
      backgroundColor: palette.surface,
      borderRadius: 20,
      padding: 20,
      borderWidth: 1,
      borderColor: palette.borderLight,
      marginBottom: 20,
      ...baseShadow,
    },
    recommendationTitle: {
      fontSize: 15,
      fontWeight: '700',
      color: palette.textPrimary,
      marginBottom: 8,
    },
    recommendationText: {
      fontSize: 14,
      color: palette.textSecondary,
      lineHeight: 20,
    },
    ratingCard: {
      backgroundColor: palette.cream,
      borderRadius: 20,
      padding: 20,
      marginBottom: 20,
      borderWidth: 1,
      borderColor: 'rgba(255,255,255,0.4)',
      ...baseShadow,
    },
    ratingContent: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 12,
    },
    ratingLabel: {
      fontSize: 14,
      fontWeight: '600',
      color: palette.textPrimary,
    },
    ratingStars: {
      flexDirection: 'row',
      gap: 8,
    },
    starButton: {
      padding: 4,
    },
    starIcon: {
      fontSize: 24,
      color: 'rgba(92,82,72,0.3)',
    },
    starIconFilled: {
      color: palette.warning,
    },
    favoriteButton: {
      paddingHorizontal: 16,
      paddingVertical: 8,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: palette.border,
      backgroundColor: palette.surface,
    },
    favoriteButtonActive: {
      backgroundColor: 'rgba(255,140,66,0.12)',
      borderColor: palette.accent,
    },
    favoriteText: {
      fontSize: 13,
      fontWeight: '600',
      color: palette.textSecondary,
    },
    favoriteTextActive: {
      color: palette.accent,
    },
    brewingSection: {
      marginBottom: 20,
    },
    sectionTitle: {
      fontSize: 16,
      fontWeight: '700',
      color: palette.textPrimary,
      marginBottom: 12,
    },
    brewingGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 10,
    },
    brewingChip: {
      paddingVertical: 10,
      paddingHorizontal: 18,
      borderRadius: 20,
      backgroundColor: palette.surface,
      borderWidth: 2,
      borderColor: palette.borderLight,
    },
    brewingChipSelected: {
      backgroundColor: palette.primary,
      borderColor: 'transparent',
    },
    brewingChipText: {
      fontSize: 13,
      fontWeight: '600',
      color: palette.textSecondary,
    },
    brewingChipTextSelected: {
      color: '#FFFFFF',
    },
    tasteSection: {
      marginBottom: 24,
    },
    purchaseSection: {
      marginBottom: 24,
    },
    tasteInputContainer: {
      backgroundColor: palette.surface,
      borderRadius: 20,
      borderWidth: 1,
      borderColor: palette.borderLight,
      padding: 4,
    },
    tasteInput: {
      paddingHorizontal: 16,
      paddingVertical: 12,
      fontSize: 14,
      color: palette.textPrimary,
    },
    generateButton: {
      borderRadius: 18,
      overflow: 'hidden',
    },
    generateButtonDisabled: {
      opacity: 0.6,
    },
    generateButtonGradient: {
      borderRadius: 18,
      paddingVertical: 18,
      alignItems: 'center',
      justifyContent: 'center',
      flexDirection: 'row',
      gap: 8,
    },
    generateButtonText: {
      color: '#FFFFFF',
      fontSize: 16,
      fontWeight: '800',
      letterSpacing: 0.3,
    },
    recipeSection: {
      marginBottom: 32,
    },
    recipeCard: {
      backgroundColor: palette.surface,
      borderRadius: 24,
      padding: 24,
      borderWidth: 1,
      borderColor: palette.borderLight,
      ...baseShadow,
    },
    recipeHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 16,
    },
    recipeIcon: {
      width: 56,
      height: 56,
      borderRadius: 18,
      backgroundColor: palette.primary,
      alignItems: 'center',
      justifyContent: 'center',
    },
    recipeIconText: {
      fontSize: 26,
      color: '#FFFFFF',
    },
    recipeHeaderContent: {
      marginLeft: 12,
      flex: 1,
    },
    recipeTitle: {
      fontSize: 18,
      fontWeight: '700',
      color: palette.textPrimary,
    },
    recipeMethod: {
      fontSize: 13,
      color: palette.textTertiary,
      marginTop: 4,
    },
    recipeContentBox: {
      backgroundColor: palette.surfaceElevated,
      borderRadius: 16,
      padding: 20,
      marginBottom: 20,
    },
    recipeContent: {
      fontSize: 15,
      lineHeight: 22,
      color: palette.textPrimary,
    },
    recipeActions: {
      flexDirection: 'row',
      gap: 12,
    },
    actionButton: {
      flex: 1,
      borderRadius: 16,
      paddingVertical: 14,
      alignItems: 'center',
      justifyContent: 'center',
    },
    actionButtonPrimary: {
      backgroundColor: palette.primary,
    },
    actionButtonPrimaryText: {
      color: '#FFFFFF',
      fontWeight: '700',
      fontSize: 14,
    },
    actionButtonSecondary: {
      backgroundColor: palette.surface,
      borderWidth: 2,
      borderColor: palette.border,
    },
    actionButtonSecondaryText: {
      color: palette.textPrimary,
      fontWeight: '700',
      fontSize: 14,
    },
    actionButtons: {
      flexDirection: 'row',
      gap: 12,
      marginBottom: 20,
    },
    button: {
      flex: 1,
      borderRadius: 16,
      paddingVertical: 14,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: palette.primary,
      ...baseShadow,
    },
    buttonSecondary: {
      backgroundColor: palette.surface,
      borderWidth: 2,
      borderColor: palette.border,
      ...baseShadow,
    },
    buttonSelected: {
      transform: [{ scale: 1.02 }],
      backgroundColor: 'rgba(255,140,66,0.12)',
      borderColor: palette.accent,
    },
    buttonDisabled: {
      opacity: 0.6,
    },
    buttonText: {
      color: '#FFFFFF',
      fontSize: 14,
      fontWeight: '700',
    },
    buttonTextSecondary: {
      color: palette.textPrimary,
    },
    submitButton: {
      flex: 1,
      backgroundColor: palette.accent,
      borderWidth: 0,
    },
    fab: {
      position: 'absolute',
      bottom: 32,
      right: 32,
      width: 56,
      height: 56,
      borderRadius: 28,
      backgroundColor: palette.accent,
      alignItems: 'center',
      justifyContent: 'center',
      opacity: 0,
      ...baseShadow,
    },
    fabVisible: {
      opacity: 1,
    },
    fabIcon: {
      fontSize: 24,
      color: '#FFFFFF',
    },
    loadingOverlay: {
      ...StyleSheet.absoluteFillObject,
      backgroundColor: 'rgba(0,0,0,0.6)',
      alignItems: 'center',
      justifyContent: 'center',
    },
    offlineModalOverlay: {
      flex: 1,
      backgroundColor: 'rgba(0,0,0,0.55)',
      alignItems: 'center',
      justifyContent: 'center',
      padding: 24,
    },
    offlineModalContent: {
      width: '100%',
      maxWidth: 360,
      backgroundColor: palette.surface,
      borderRadius: 24,
      padding: 24,
      alignItems: 'center',
      borderWidth: 1,
      borderColor: palette.borderLight,
      ...baseShadow,
    },
    offlineModalText: {
      fontSize: 14,
      color: palette.textPrimary,
      textAlign: 'center',
      marginBottom: 16,
      lineHeight: 20,
    },
    loadingContainer: {
      backgroundColor: palette.surface,
      paddingHorizontal: 32,
      paddingVertical: 24,
      borderRadius: 24,
      alignItems: 'center',
      ...baseShadow,
    },
    loadingText: {
      marginTop: 12,
      fontSize: 14,
      fontWeight: '600',
      color: palette.textPrimary,
    },
    cameraContainer: {
      flex: 1,
      backgroundColor: '#000',
    },
    camera: {
      flex: 1,
    },
    cameraOverlay: {
      ...StyleSheet.absoluteFillObject,
      justifyContent: 'space-between',
    },
    cameraHeader: {
      paddingTop: Platform.OS === 'ios' ? 60 : 40,
      paddingHorizontal: 24,
      flexDirection: 'row',
      justifyContent: 'flex-end',
    },
    cameraCloseButton: {
      width: 40,
      height: 40,
      borderRadius: 12,
      backgroundColor: 'rgba(0,0,0,0.4)',
      alignItems: 'center',
      justifyContent: 'center',
    },
    cameraCloseText: {
      color: '#FFFFFF',
      fontSize: 18,
    },
    scanFrame: {
      alignSelf: 'center',
      width: '75%',
      aspectRatio: 1,
      marginTop: '20%',
    },
    scanCorner: {
      position: 'absolute',
      width: 40,
      height: 40,
      borderColor: '#FFFFFF',
      borderWidth: 4,
    },
    scanCornerTL: {
      top: 0,
      left: 0,
      borderBottomWidth: 0,
      borderRightWidth: 0,
    },
    scanCornerTR: {
      top: 0,
      right: 0,
      borderBottomWidth: 0,
      borderLeftWidth: 0,
    },
    scanCornerBL: {
      bottom: 0,
      left: 0,
      borderTopWidth: 0,
      borderRightWidth: 0,
    },
    scanCornerBR: {
      bottom: 0,
      right: 0,
      borderTopWidth: 0,
      borderLeftWidth: 0,
    },
    cameraInstructions: {
      alignItems: 'center',
      paddingBottom: 40,
    },
    cameraInstructionText: {
      color: '#FFFFFF',
      fontSize: 16,
      fontWeight: '600',
    },
    cameraControls: {
      alignItems: 'center',
      paddingBottom: 48,
    },
    captureButton: {
      width: 86,
      height: 86,
      borderRadius: 43,
      borderWidth: 6,
      borderColor: '#FFFFFF',
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: 'rgba(255,255,255,0.1)',
    },
    captureInner: {
      width: 58,
      height: 58,
      borderRadius: 29,
      backgroundColor: '#FFFFFF',
    },
    scanReviewContainer: {
      paddingBottom: 24,
    },
    scanCoffeeCard: {
      backgroundColor: palette.surface,
      borderRadius: 28,
      padding: 24,
      marginBottom: 20,
      borderWidth: 1,
      borderColor: 'rgba(200,168,130,0.35)',
      shadowColor: palette.shadow,
      shadowOffset: { width: 0, height: 10 },
      shadowOpacity: 0.12,
      shadowRadius: 22,
      elevation: 6,
    },
    scanBadgeRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginBottom: 16,
    },
    scanBadge: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingVertical: 6,
      paddingHorizontal: 12,
      borderRadius: 999,
      backgroundColor: '#7FB069',
    },
    scanBadgeIcon: {
      fontSize: 12,
      color: '#FFFFFF',
      marginRight: 6,
    },
    scanBadgeText: {
      fontSize: 12,
      fontWeight: '700',
      color: '#FFFFFF',
      letterSpacing: 0.3,
    },
    scanMatchPill: {
      paddingHorizontal: 14,
      paddingVertical: 6,
      borderRadius: 999,
      backgroundColor: 'rgba(255,179,0,0.18)',
      borderWidth: 1,
      borderColor: 'rgba(255,179,0,0.32)',
    },
    scanMatchText: {
      fontSize: 12,
      fontWeight: '700',
      color: palette.warning,
    },
    scanCoffeeName: {
      fontSize: 28,
      fontWeight: '800',
      color: palette.textPrimary,
      letterSpacing: -0.3,
      marginBottom: 8,
    },
    scanCoffeeDetails: {
      fontSize: 14,
      color: palette.textSecondary,
      marginBottom: 12,
    },
    scanNotesRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      marginBottom: 16,
    },
    scanNoteChip: {
      paddingHorizontal: 12,
      paddingVertical: 6,
      borderRadius: 999,
      backgroundColor: palette.surfaceElevated,
      borderWidth: 1,
      borderColor: 'rgba(200,168,130,0.35)',
      marginRight: 8,
      marginBottom: 8,
    },
    scanNoteChipText: {
      fontSize: 12,
      color: palette.textSecondary,
    },
    scanTextInputContainer: {
      marginTop: 12,
    },
    scanTextInput: {
      minHeight: 140,
      borderRadius: 18,
      padding: 18,
      borderWidth: 1,
      borderColor: 'rgba(200,168,130,0.3)',
      backgroundColor: palette.surfaceElevated,
      fontSize: 14,
      color: palette.textPrimary,
      lineHeight: 20,
    },
    scanRatingWrapper: {
      borderRadius: 24,
      marginBottom: 20,
      shadowColor: palette.shadow,
      shadowOffset: { width: 0, height: 10 },
      shadowOpacity: 0.12,
      shadowRadius: 20,
      elevation: 6,
    },
    scanRatingCard: {
      borderRadius: 24,
      padding: 20,
    },
    scanRatingHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 12,
    },
    scanRatingTitle: {
      fontSize: 16,
      fontWeight: '800',
      color: palette.textPrimary,
    },
    scanRatingValue: {
      fontSize: 22,
      fontWeight: '800',
      color: palette.warning,
    },
    scanStarsRow: {
      flexDirection: 'row',
      justifyContent: 'center',
      marginBottom: 12,
    },
    scanStarButton: {
      paddingHorizontal: 8,
      paddingVertical: 4,
    },
    scanStarIcon: {
      fontSize: 28,
      color: 'rgba(120,100,80,0.3)',
    },
    scanStarIconActive: {
      color: palette.warning,
    },
    scanFavoriteButton: {
      marginTop: 4,
      alignSelf: 'center',
      paddingHorizontal: 18,
      paddingVertical: 8,
      borderRadius: 999,
      backgroundColor: 'rgba(255,255,255,0.85)',
      borderWidth: 1,
      borderColor: 'rgba(200,168,130,0.35)',
    },
    scanFavoriteButtonActive: {
      backgroundColor: 'rgba(255,179,0,0.25)',
      borderColor: 'rgba(255,179,0,0.5)',
    },
    scanFavoriteText: {
      fontSize: 13,
      fontWeight: '700',
      color: palette.textSecondary,
    },
    scanFavoriteTextActive: {
      color: palette.warning,
    },
    scanMethodSection: {
      marginBottom: 20,
    },
    scanSectionHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 16,
    },
    scanSectionIcon: {
      width: 40,
      height: 40,
      borderRadius: 12,
      backgroundColor: palette.primary,
      alignItems: 'center',
      justifyContent: 'center',
      marginRight: 12,
    },
    scanSectionIconText: {
      fontSize: 18,
      color: '#FFFFFF',
    },
    scanSectionTitle: {
      fontSize: 18,
      fontWeight: '800',
      color: palette.textPrimary,
    },
    scanMethodGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      justifyContent: 'space-between',
    },
    scanMethodButton: {
      flexBasis: '31%',
      backgroundColor: palette.surface,
      borderRadius: 18,
      paddingVertical: 14,
      alignItems: 'center',
      borderWidth: 2,
      borderColor: 'rgba(200,168,130,0.25)',
      marginBottom: 12,
      overflow: 'hidden',
    },
    scanMethodButtonSelected: {
      backgroundColor: palette.primary,
      borderColor: 'rgba(107,68,35,0.6)',
    },
    scanMethodEmoji: {
      fontSize: 22,
      marginBottom: 6,
    },
    scanMethodName: {
      fontSize: 12,
      fontWeight: '800',
      color: palette.textSecondary,
    },
    scanMethodNameSelected: {
      color: '#FFFFFF',
    },
    scanMethodTime: {
      fontSize: 11,
      color: 'rgba(92,82,72,0.6)',
      marginTop: 2,
    },
    scanMethodTimeSelected: {
      color: 'rgba(255,255,255,0.85)',
    },
    scanTipWrapper: {
      marginBottom: 20,
      borderRadius: 22,
      shadowColor: palette.shadow,
      shadowOffset: { width: 0, height: 10 },
      shadowOpacity: 0.14,
      shadowRadius: 24,
      elevation: 6,
    },
    scanTipCard: {
      borderRadius: 22,
      padding: 18,
    },
    scanTipHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 10,
    },
    scanTipIcon: {
      width: 28,
      height: 28,
      borderRadius: 8,
      backgroundColor: 'rgba(255,255,255,0.25)',
      alignItems: 'center',
      justifyContent: 'center',
      marginRight: 8,
    },
    scanTipIconText: {
      fontSize: 14,
      color: '#FFFFFF',
    },
    scanTipLabel: {
      fontSize: 11,
      fontWeight: '900',
      letterSpacing: 1,
      color: 'rgba(255,255,255,0.95)',
    },
    scanTipText: {
      fontSize: 13,
      lineHeight: 20,
      color: '#FFFFFF',
    },
    scanPreferenceSection: {
      marginBottom: 20,
    },
    scanPreferenceCard: {
      backgroundColor: palette.surface,
      borderRadius: 24,
      padding: 20,
      borderWidth: 1,
      borderColor: 'rgba(200,168,130,0.25)',
      shadowColor: palette.shadow,
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.1,
      shadowRadius: 18,
      elevation: 4,
    },
    scanPreferencePrompt: {
      fontSize: 14,
      color: palette.textSecondary,
      lineHeight: 20,
      marginBottom: 12,
    },
    scanPreferenceInput: {
      minHeight: 130,
      borderRadius: 18,
      borderWidth: 2,
      borderColor: 'rgba(200,168,130,0.35)',
      backgroundColor: palette.surfaceElevated,
      padding: 16,
      fontSize: 14,
      color: palette.textPrimary,
      lineHeight: 20,
    },
    scanSuggestionsRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      marginTop: 12,
    },
    scanSuggestionPill: {
      paddingHorizontal: 14,
      paddingVertical: 8,
      borderRadius: 999,
      backgroundColor: palette.surfaceElevated,
      borderWidth: 1,
      borderColor: 'rgba(200,168,130,0.35)',
      marginRight: 8,
      marginBottom: 8,
    },
    scanSuggestionPillSelected: {
      backgroundColor: palette.warning,
      borderColor: palette.warning,
    },
    scanSuggestionText: {
      fontSize: 13,
      color: palette.textSecondary,
      fontWeight: '600',
    },
    scanSuggestionTextSelected: {
      color: palette.textPrimary,
    },
    scanGenerateBar: {
      marginTop: 4,
      marginBottom: 32,
      padding: 16,
      borderRadius: 20,
      backgroundColor: 'rgba(255,255,255,0.9)',
      shadowColor: palette.shadow,
      shadowOffset: { width: 0, height: 12 },
      shadowOpacity: 0.18,
      shadowRadius: 28,
      elevation: 10,
    },
  });
};
